plugins {
    id 'java'
}

group = 'com.epam.jmp'
version = '0.0.1-SNAPSHOT'
description = 'Java Advanced - Module 5 - Clean Code'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
